#ifndef __HIERRNO_SERVICE_CAPSHD_H__
#define __HIERRNO_SERVICE_CAPSHD_H__

#include "../hierrno.h"

#define HIERRNO_SERVICE_CAPSHD_FAIL                 (HIERRNO_SERVICE_CAPSHD | 0x1) //方法调用失败
#define HIERRNO_SERVICE_CAPSHD_APSWITCH_FAILED      (HIERRNO_SERVICE_CAPSHD | 0x2) //切换AP模式失败
#define HIERRNO_SERVICE_CAPSHD_SLAVE_NOT_FOUND      (HIERRNO_SERVICE_CAPSHD | 0x3) //设备没有找到
#define HIERRNO_SERVICE_CAPSHD_NO_NEED              (HIERRNO_SERVICE_CAPSHD | 0x4) //不需要的操作

#endif
