#ifndef __HIERRNO_SERVICE_HIMSG_H__
#define __HIERRNO_SERVICE_HIMSG_H__

#include "../hierrno.h"

#define HIERRNO_RET_INVALID_ARGUMENTS      (HIERRNO_SERVICE_HIMSG | 0x9001) //无效参数
#define HIERRNO_RET_INTERNAL_ERROR         (HIERRNO_SERVICE_HIMSG | 0x9002) //内部错误
#define HIERRNO_RET_RESOURCE_EXCEEDED      (HIERRNO_SERVICE_HIMSG | 0x9003) //资源不足
#define HIERRNO_RET_DISCONNECTED           (HIERRNO_SERVICE_HIMSG | 0x9004) //链接已断开
#define HIERRNO_RET_TIMED_OUT              (HIERRNO_SERVICE_HIMSG | 0x9005) //操作超时
#define HIERRNO_RET_DUPLICATE_REGISTER     (HIERRNO_SERVICE_HIMSG | 0x9006) //重复注册
#define HIERRNO_RET_UNINITIALIZED          (HIERRNO_SERVICE_HIMSG | 0x9007) //初始化失败或未初始化
#define HIERRNO_RET_CALLBACK_NOT_FOUND     (HIERRNO_SERVICE_HIMSG | 0x9008) //找不到回调函数
#define HIERRNO_RET_UNKNOWN_TYPE           (HIERRNO_SERVICE_HIMSG | 0x9010) //未知类型
#define HIERRNO_RET_OBJECT_NOT_FOUND       (HIERRNO_SERVICE_HIMSG | 0x9011) //找不到对象
#define HIERRNO_RET_EVENT_NOT_FOUND        (HIERRNO_SERVICE_HIMSG | 0x9012) //找不到事件

#endif