#ifndef __HIERRNO_SERVICE_HISCRIPT_H__
#define __HIERRNO_SERVICE_HISCRIPT_H__

#include "../hierrno.h"

#define HIERRNO_SERVICE_HISCRIPT_INTERNAL       (HIERRNO_SERVICE_HISCRIPT | 0x100) //内部错误
#define HIERRNO_SERVICE_HISCRIPT_NO_METHOD      (HIERRNO_SERVICE_HISCRIPT | 0x200) //没有此方法
#define HIERRNO_SERVICE_HISCRIPT_SCRIPT_KILLED  (HIERRNO_SERVICE_HISCRIPT | 0x300) //脚本被信号终止

#endif
