#ifndef __HIERRNO_SERVICE_IFTTT_H__
#define __HIERRNO_SERVICE_IFTTT_H__

#include "../hierrno.h"

/*
0x00: Success
0x01: Unknown Error
0x02: Agument Error
0x03: Config Is Exist
0x04: Not Enough Memory
0x05: Not Find Config
*/

#define HIERRNO_SERVICE_IFTTT_ERR_SUCCESS			(HIERRNO_SERVICE_IFTTT | 0x00) //执行成功
#define HIERRNO_SERVICE_IFTTT_ERR_FAILED			(HIERRNO_SERVICE_IFTTT | 0x01) //未知错误
#define HIERRNO_SERVICE_IFTTT_ERR_ARGUMENT_ERROR	(HIERRNO_SERVICE_IFTTT | 0x02) //参数错误
#define HIERRNO_SERVICE_IFTTT_ERR_CONFIGISEXIST		(HIERRNO_SERVICE_IFTTT | 0x03) //配置已存在
#define HIERRNO_SERVICE_IFTTT_ERR_NOTENOUGHMEMORY	(HIERRNO_SERVICE_IFTTT | 0x04) //内存不够
#define HIERRNO_SERVICE_IFTTT_ERR_NOTFINDCONFIG		(HIERRNO_SERVICE_IFTTT | 0x05) //没有找到此配置

#endif
