#ifndef __HIERRNO_SERVICE_UKBACKUP_H__
#define __HIERRNO_SERVICE_UKBACKUP_H__

#include "../hierrno.h"

#define HIERRNO_SERVICE_UKBACKUP_NO_METHOD      (HIERRNO_SERVICE_UKBACKUP | 0x1) //没有该方法
#define HIERRNO_SERVICE_UKBACKUP_NO_BACKUP      (HIERRNO_SERVICE_UKBACKUP | 0x2) //没有可用备份
#define HIERRNO_SERVICE_UKBACKUP_NO_DATA        (HIERRNO_SERVICE_UKBACKUP | 0x3) //没有数据分区
#define HIERRNO_SERVICE_UKBACKUP_PKG_FAILED     (HIERRNO_SERVICE_UKBACKUP | 0x4) //备份压缩失败
#define HIERRNO_SERVICE_UKBACKUP_ENC_FAILED     (HIERRNO_SERVICE_UKBACKUP | 0x5) //备份加密失败
#define HIERRNO_SERVICE_UKBACKUP_UNPKG_FAILED   (HIERRNO_SERVICE_UKBACKUP | 0x6) //备份解压失败

#endif