#ifndef __HIERRNO_HOMECLOUD_DOWNLOAD_H__
#define __HIERRNO_HOMECLOUD_DOWNLOAD_H__

#include ../hierrno.h

#define HIERRNO_HOMECLOUD_DOWNLOAD_NET_TIMEOUT                (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1) //网络连接超时
#define HIERRNO_HOMECLOUD_DOWNLOAD_DEV_TIMEOUT                (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2) //设备响应超时
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_INNER               (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_IO                    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x4) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_DEV_SPACE                  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x5) //设备空间不足
#define HIERRNO_HOMECLOUD_DOWNLOAD_PIPO_READ                  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x6) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_FILENAMETOOLONG       (HIERRNO_HOMECLOUD_DOWNLOAD | 0x7) //文件名过长
#define HIERRNO_HOMECLOUD_DOWNLOAD_DATABASE_ROW_NOTFOUDPRO    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x8) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_TRANSLATETORRENT      (HIERRNO_HOMECLOUD_DOWNLOAD | 0x9) //解析种子文件失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_RESOURCE_URLCHANGED        (HIERRNO_HOMECLOUD_DOWNLOAD | 0xa) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SOCEKT_HANDLEFAILD         (HIERRNO_HOMECLOUD_DOWNLOAD | 0xb) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_NET_NOTACCESS              (HIERRNO_HOMECLOUD_DOWNLOAD | 0xc) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_DATACHECKDUMP         (HIERRNO_HOMECLOUD_DOWNLOAD | 0xd) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_NOTGETGID             (HIERRNO_HOMECLOUD_DOWNLOAD | 0xe) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_CRAETEORWRITE         (HIERRNO_HOMECLOUD_DOWNLOAD | 0xf) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_WRITE                 (HIERRNO_HOMECLOUD_DOWNLOAD | 0x10) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_CACHESPASE_CRTGID   (HIERRNO_HOMECLOUD_DOWNLOAD | 0x11) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_CACHESPASE_CRTFILE  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x12) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_NOTENOUGHSPACE        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x13) //设备空间不足
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_FILEREAD_HANDLEGID  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x14) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_SYSNOTSURP_4G         (HIERRNO_HOMECLOUD_DOWNLOAD | 0x15) //设备空间不足
#define HIERRNO_HOMECLOUD_DOWNLOAD_RESOURCER_NOTGETRESOURCE   (HIERRNO_HOMECLOUD_DOWNLOAD | 0x16) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_RESOURCER_TRYTOFIND        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x17) //创建下载任务失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_TMPFILEDELETED        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x18) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_URL_NOTALLOWED      (HIERRNO_HOMECLOUD_DOWNLOAD | 0x19) //创建下载任务失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_SAMETASKFOUND         (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1a) //任务已存在
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_WAITINGCREATING       (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1b) //任务已经在等待创建中
#define HIERRNO_HOMECLOUD_DOWNLOAD_DEV_NOTENOUGHSPACE         (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1c) //磁盘空间不足
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_FILEPATH              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1d) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BT                    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1e) //bt种子错误
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BTTOOBIG              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x1f) //bt种子文件太大
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BTTOOMANYTASK         (HIERRNO_HOMECLOUD_DOWNLOAD | 0x20) //bt任务个数过多
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_HTTPREQERR            (HIERRNO_HOMECLOUD_DOWNLOAD | 0x21) //http请求错误
#define HIERRNO_HOMECLOUD_DOWNLOAD_NET_HEALTH_ERR             (HIERRNO_HOMECLOUD_DOWNLOAD | 0x22) //网络状况不佳
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_PERM_DENIED           (HIERRNO_HOMECLOUD_DOWNLOAD | 0x23) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_NOTFOUND              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x24) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_RAMNOTENOUGH        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x25) //内存不足
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_ARG                 (HIERRNO_HOMECLOUD_DOWNLOAD | 0x26) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SOCKET_CLOSED              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x27) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_CANNOTWRITE           (HIERRNO_HOMECLOUD_DOWNLOAD | 0x28) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_DNS                 (HIERRNO_HOMECLOUD_DOWNLOAD | 0x29) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_PATH_ERR              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2a) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_URL_NOTALLOWED        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2b) //创建下载任务失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_URL_NOTALLOWED             (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2c) //创建下载任务失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_SAVEPATH              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2d) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_NAME                  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2e) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_REDOWNLOAD            (HIERRNO_HOMECLOUD_DOWNLOAD | 0x2f) //重复下载了相同的任务
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_FAILDOPENOLDFILE      (HIERRNO_HOMECLOUD_DOWNLOAD | 0x30) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_HTTP_UNCLEAR        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x31) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_WRONGRANGE          (HIERRNO_HOMECLOUD_DOWNLOAD | 0x32) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_HTTPREQ_UNUSUAL       (HIERRNO_HOMECLOUD_DOWNLOAD | 0x33) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_HTTP_302ADDR        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x34) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_NOTFOUND2             (HIERRNO_HOMECLOUD_DOWNLOAD | 0x35) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_PROXY_AUTH          (HIERRNO_HOMECLOUD_DOWNLOAD | 0x36) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_REQRANGEOVERFLOW    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x37) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_GETREMOTEFILESIZE   (HIERRNO_HOMECLOUD_DOWNLOAD | 0x38) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_RANGE_NOTALLOWED    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x39) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_HTTPREQ_UNUSUAL2      (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3a) //http请求异常
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_SERVICENOTALLOWED   (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3b) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_SSL                   (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3c) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_RANGEREQ            (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3d) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_NOREMOTEPATH        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3e) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_NOTFOUND2             (HIERRNO_HOMECLOUD_DOWNLOAD | 0x3f) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_USER_NOTALLOWED     (HIERRNO_HOMECLOUD_DOWNLOAD | 0x40) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_SERVER_FTP_ACK             (HIERRNO_HOMECLOUD_DOWNLOAD | 0x41) //任务下载失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BTDATA                (HIERRNO_HOMECLOUD_DOWNLOAD | 0x42) //bt下载部分数据无法进行修正
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BT_GCID_CHECK         (HIERRNO_HOMECLOUD_DOWNLOAD | 0x43) //bt下载的文件gcid校验出错
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BT_LOWTIMEISUP        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x44) //该bt文件的慢速时长超过了预设最大慢速时长
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BT_CID                (HIERRNO_HOMECLOUD_DOWNLOAD | 0x45) //bt数据cid校验出错
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_BT_NOSOURCEORNOSPACE  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x46) //BT种子没资源或磁盘空间不足
#define HIERRNO_HOMECLOUD_DOWNLOAD_TASK_MAGNET                (HIERRNO_HOMECLOUD_DOWNLOAD | 0x47) //磁力链任务建立失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_DEV_BIN_IMAGE              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x48) //设备固件问题


#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_FILE_SRCFILENOTFOUND    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x100) //文件下载成功，但文件操作失败：源文件或路径不存在
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_FILE_DESTDIRNOTFOUND    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x101) //文件下载成功，但文件操作失败：目标目录不存在
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_FILE_CANNOTGETFILESIZE  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x102) //文件下载成功，但文件操作失败：获取目标目录大小失败
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_FILE_NOENOUGHSPACELEFT  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x103) //文件下载成功，但文件操作失败：目标目录空间不足

#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_ABSDIR_PATH_NOTALLOWED  (HIERRNO_HOMECLOUD_DOWNLOAD | 0x200) //download_absdir 错误：此目录不能作为下载目录，UG：/tmp/storage/..
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_ABSDIR_INANOTHERPART    (HIERRNO_HOMECLOUD_DOWNLOAD | 0x201) //download_absdir 错误：download_absdir 所在分区与partition设置的不一致
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_ABSDIR_DIR_NOTEXIST     (HIERRNO_HOMECLOUD_DOWNLOAD | 0x202) //download_absdir 错误：此目录不存在


#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_TASKNOTFOUND            (HIERRNO_HOMECLOUD_DOWNLOAD | 0x300) //任务未找到
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_LOADERUNUSUAL           (HIERRNO_HOMECLOUD_DOWNLOAD | 0x301) //下载器异常
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_TASK_NOTEXIST           (HIERRNO_HOMECLOUD_DOWNLOAD | 0x302) //任务不存在
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_DEV_UNABLE              (HIERRNO_HOMECLOUD_DOWNLOAD | 0x303) //找不到存储设备,或设备不可用，请检查
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_TASK_HAD_EXISTED        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x304) //任务已存在
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_MMC                     (HIERRNO_HOMECLOUD_DOWNLOAD | 0x305) //存储卡异常
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_URL_PATH                (HIERRNO_HOMECLOUD_DOWNLOAD | 0x306) //url不合法
#define HIERRNO_HOMECLOUD_DOWNLOAD_DL_UNCLEAR                 (HIERRNO_HOMECLOUD_DOWNLOAD | 0x307) //创建下载任务失败 ##


#define HIERRNO_HOMECLOUD_DOWNLOAD_INFO_TABLE_NOTFOUND        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x400) //error_map_table 表中没有找到对应错误信息


#define HIERRNO_HOMECLOUD_DOWNLOAD_D_APPNAMENEEDED            (HIERRNO_HOMECLOUD_DOWNLOAD | 0x500) //请输入插件名app_name
#define HIERRNO_HOMECLOUD_DOWNLOAD_D_LOADER_A_OUTRUNNING      (HIERRNO_HOMECLOUD_DOWNLOAD | 0x501) //下载器A未启动
#define HIERRNO_HOMECLOUD_DOWNLOAD_D_LOADER_X_OUTRUNNING      (HIERRNO_HOMECLOUD_DOWNLOAD | 0x502) //下载器X未启动, 请尝试 重新拔插SD卡 或 重装'迅雷远程下载'插件
#define HIERRNO_HOMECLOUD_DOWNLOAD_D_BIN_FILE_DELETION        (HIERRNO_HOMECLOUD_DOWNLOAD | 0x503) //程序缺失, 请重新安装'迅雷远程下载'插件
#define HIERRNO_HOMECLOUD_DOWNLOAD_D_DATADB_KEY_ERR           (HIERRNO_HOMECLOUD_DOWNLOAD | 0x504) //key error
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_FS_TOOLARGE           (HIERRNO_HOMECLOUD_DOWNLOAD | 0x505) //文件大小超过文件系统限制
#define HIERRNO_HOMECLOUD_DOWNLOAD_FILE_FS_GETTYPEERR         (HIERRNO_HOMECLOUD_DOWNLOAD | 0x506) //获取文件系统格式错误
#define HIERRNO_HOMECLOUD_DOWNLOAD_D_DATADB_NOTFOUND          (HIERRNO_HOMECLOUD_DOWNLOAD | 0x507) //数据库不存在此条数据
#endif
