#ifndef _PARENT_CTRL_ERRNO_
#define _PARENT_CTRL_ERRNO_

#include "../hierrno.h"

#define HIERRNO_PARENTCTRL_PARAM_ERROR          (HIERRNO_NETWORK_PARENTCTRL | 0x01) //参数错误
#define HIERRNO_PARENTCTRL_ILLEGAL_RULEID       (HIERRNO_NETWORK_PARENTCTRL | 0x02) //规则id不合法
#define HIERRNO_PARENTCTRL_RULEID_CONFLICT      (HIERRNO_NETWORK_PARENTCTRL | 0x03) //规则id重复
#define HIERRNO_PARENTCTRL_RULEID_NOT_EXIST     (HIERRNO_NETWORK_PARENTCTRL | 0x04) //规则id不存在
#define HIERRNO_PARENTCTRL_CONFIG_FAILED        (HIERRNO_NETWORK_PARENTCTRL | 0x05) //配置执行错误
#define HIERRNO_PARENTCTRL_PARTIAL_CONFIG_FAILED     (HIERRNO_NETWORK_PARENTCTRL | 0x06) //配置执行错误(部分)
#define HIERRNO_PARENTCTRL_MULTI_MAC_NOT_SUPPORT     (HIERRNO_NETWORK_PARENTCTRL | 0x07) //不支持多个mac
#define HIERRNO_PARENTCTRL_MULTI_RULES_NOT_SUPPORT   (HIERRNO_NETWORK_PARENTCTRL | 0x08) //不支持多个规则
#define HIERRNO_PARENTCTRL_QUERY_FAILED              (HIERRNO_NETWORK_PARENTCTRL | 0x09) //查询失败
#define HIERRNO_PARENTCTRL_OPTION_NOT_SUPPORT        (HIERRNO_NETWORK_PARENTCTRL | 0x0A) //暂不支持的操作

#endif
