#ifndef _SMARTTUNNEL_ERRNO_
#define _SMARTTUNNEL_ERRNO_

#include "../hierrno.h"

#define HIERRNO_ST_NAME_EXIST			(HIERRNO_NETWORK_SMARTTUNNEL | 0x01) //插件名称已经存在
#define HIERRNO_ST_PARAM_NULL			(HIERRNO_NETWORK_SMARTTUNNEL | 0x02) //参数不能为空
#define HIERRNO_ST_PLUGIN_UNINSTALL		(HIERRNO_NETWORK_SMARTTUNNEL | 0x03) //插件未安装
#define HIERRNO_ST_BASIC_FUNC_UNREG		(HIERRNO_NETWORK_SMARTTUNNEL | 0x04) //对应协议的basic_config函数未注册
#define HIERRNO_ST_INGRESS_FUNC_UNREG	(HIERRNO_NETWORK_SMARTTUNNEL | 0x05) //对应协议的ingress_rule函数未注册
#define HIERRNO_ST_INGRESS_FUNC_UNEXIST	(HIERRNO_NETWORK_SMARTTUNNEL | 0x06) //导入规则函数不存在
#define HIERRNO_ST_FILE_CREATED_FAILED	(HIERRNO_NETWORK_SMARTTUNNEL | 0x07) //建立文件失败
#define HIERRNO_ST_PARAM_ERROR			(HIERRNO_NETWORK_SMARTTUNNEL | 0x08) //参数错误
#define HIERRNO_ST_ADV_FUNC_UNREG		(HIERRNO_NETWORK_SMARTTUNNEL | 0x09) //对应协议的advanced_config函数未注册
#define HIERRNO_ST_API_ERROR			(HIERRNO_NETWORK_SMARTTUNNEL | 0x0a) //接口不支持
#define HIERRNO_ST_OPT_ERROR			(HIERRNO_NETWORK_SMARTTUNNEL | 0x0b) //操作失败

#endif
